In [7]:
!pip install faiss-cpu

Collecting faiss-cpu
  Downloading faiss_cpu-1.13.2-cp311-cp311-win_amd64.whl.metadata (7.6 kB)
Requirement already satisfied: numpy<3.0,>=1.25.0 in c:\users\dell\anaconda3\lib\site-packages (from faiss-cpu) (1.26.4)
Requirement already satisfied: packaging in c:\users\dell\anaconda3\lib\site-packages (from faiss-cpu) (25.0)
Downloading faiss_cpu-1.13.2-cp311-cp311-win_amd64.whl (18.9 MB)
   ---------------------------------------- 0.0/18.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/18.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/18.9 MB 435.7 kB/s eta 0:00:44
   ---------------------------------------- 0.1/18.9 MB 550.5 kB/s eta 0:00:35
   ---------------------------------------- 0.1/18.9 MB 658.3 kB/s eta 0:00:29
   ---------------------------------------- 0.2/18.9 MB 1.1 MB/s eta 0:00:17
    --------------------------------------- 0.3/18.9 MB 1.1 MB/s eta 0:00:17
    --------------------------------------- 0.5/18.9 MB 1.6 MB/s eta 0:00:12
   - -------------------------------------- 0.6/18.9 MB 1.9 MB/s eta 0:00:10
   - -------------------------------------- 0.7/18.9 MB 2.0 MB/s eta 0:00:09
   - -------------------------------------- 0.7/18.9 MB 2.0 MB/s eta 0:00:09
   - -------------------------------------- 0.7/18.9 MB 1.6 MB/s eta 0:00:12
   - -------------------------------------- 0.7/18.9 MB 1.6 MB/s eta 0:00:12
   -- ------------------------------------- 1.2/18.9 MB 2.2 MB/s eta 0:00:08
   -- ------------------------------------- 1.3/18.9 MB 2.2 MB/s eta 0:00:09
   --- ------------------------------------ 1.5/18.9 MB 2.3 MB/s eta 0:00:08
   --- ------------------------------------ 1.6/18.9 MB 2.4 MB/s eta 0:00:08
   --- ------------------------------------ 1.6/18.9 MB 2.4 MB/s eta 0:00:08
   --- ------------------------------------ 1.6/18.9 MB 2.1 MB/s eta 0:00:09
   --- ------------------------------------ 1.6/18.9 MB 2.1 MB/s eta 0:00:09
   ---- ----------------------------------- 2.2/18.9 MB 2.5 MB/s eta 0:00:07
   ---- ----------------------------------- 2.2/18.9 MB 2.4 MB/s eta 0:00:07
   ---- ----------------------------------- 2.2/18.9 MB 2.3 MB/s eta 0:00:08
   ----- ---------------------------------- 2.4/18.9 MB 2.3 MB/s eta 0:00:08
   ----- ---------------------------------- 2.6/18.9 MB 2.4 MB/s eta 0:00:07
   ----- ---------------------------------- 2.7/18.9 MB 2.5 MB/s eta 0:00:07
   ------ --------------------------------- 2.9/18.9 MB 2.5 MB/s eta 0:00:07
   ------ --------------------------------- 3.1/18.9 MB 2.6 MB/s eta 0:00:07
   ------ --------------------------------- 3.3/18.9 MB 2.6 MB/s eta 0:00:06
   ------- -------------------------------- 3.5/18.9 MB 2.7 MB/s eta 0:00:06
   ------- -------------------------------- 3.6/18.9 MB 2.7 MB/s eta 0:00:06
   -------- ------------------------------- 3.8/18.9 MB 2.8 MB/s eta 0:00:06
   -------- ------------------------------- 4.0/18.9 MB 2.8 MB/s eta 0:00:06
   -------- ------------------------------- 4.2/18.9 MB 2.8 MB/s eta 0:00:06
   --------- ------------------------------ 4.4/18.9 MB 2.9 MB/s eta 0:00:06
   --------- ------------------------------ 4.5/18.9 MB 2.9 MB/s eta 0:00:05
   ---------- ----------------------------- 4.7/18.9 MB 2.9 MB/s eta 0:00:05
   ---------- ----------------------------- 4.9/18.9 MB 3.0 MB/s eta 0:00:05
   ---------- ----------------------------- 5.1/18.9 MB 3.0 MB/s eta 0:00:05
   ----------- ---------------------------- 5.3/18.9 MB 3.0 MB/s eta 0:00:05
   ----------- ---------------------------- 5.4/18.9 MB 3.0 MB/s eta 0:00:05
   ----------- ---------------------------- 5.6/18.9 MB 3.1 MB/s eta 0:00:05
   ------------ --------------------------- 5.8/18.9 MB 3.1 MB/s eta 0:00:05
   ------------ --------------------------- 6.0/18.9 MB 3.1 MB/s eta 0:00:05
   ------------- -------------------------- 6.2/18.9 MB 3.1 MB/s eta 0:00:05
   ------------- -------------------------- 6.3/18.9 MB 3.1 MB/s eta 0:00:05
   ------------- -------------------------- 6.5/18.9 MB 3.1 MB/s eta 0:00:04
   -------------- ------------------------- 6.7/18.9 MB 3.1 MB/s eta 0:00:04
   -------------- ------------------------- 6.9/18.9 MB 3.2 MB/s eta 0:00:04
   -------------- ------------------------- 7.0/18.9 MB 3.2 MB/s eta 0:00:04
   --------------- ------------------------ 7.2/18.9 MB 3.2 MB/s eta 0:00:04
   --------------- ------------------------ 7.4/18.9 MB 3.2 MB/s eta 0:00:04
   ---------------- ----------------------- 7.6/18.9 MB 3.2 MB/s eta 0:00:04
   ---------------- ----------------------- 7.8/18.9 MB 3.2 MB/s eta 0:00:04
   ---------------- ----------------------- 7.9/18.9 MB 3.3 MB/s eta 0:00:04
   ----------------- ---------------------- 8.1/18.9 MB 3.3 MB/s eta 0:00:04
   ----------------- ---------------------- 8.3/18.9 MB 3.3 MB/s eta 0:00:04
   ----------------- ---------------------- 8.3/18.9 MB 3.3 MB/s eta 0:00:04
   ------------------ --------------------- 8.7/18.9 MB 3.3 MB/s eta 0:00:04
   ------------------ --------------------- 8.8/18.9 MB 3.3 MB/s eta 0:00:04
   ------------------ --------------------- 8.9/18.9 MB 3.3 MB/s eta 0:00:04
   ------------------- -------------------- 9.1/18.9 MB 3.3 MB/s eta 0:00:03
   ------------------- -------------------- 9.2/18.9 MB 3.3 MB/s eta 0:00:03
   ------------------- -------------------- 9.3/18.9 MB 3.3 MB/s eta 0:00:03
   -------------------- ------------------- 9.5/18.9 MB 3.3 MB/s eta 0:00:03
   -------------------- ------------------- 9.6/18.9 MB 3.2 MB/s eta 0:00:03
   -------------------- ------------------- 9.7/18.9 MB 3.2 MB/s eta 0:00:03
   -------------------- ------------------- 9.8/18.9 MB 3.2 MB/s eta 0:00:03
   --------------------- ------------------ 9.9/18.9 MB 3.2 MB/s eta 0:00:03
   --------------------- ------------------ 10.1/18.9 MB 3.2 MB/s eta 0:00:03
   --------------------- ------------------ 10.1/18.9 MB 3.2 MB/s eta 0:00:03
   --------------------- ------------------ 10.3/18.9 MB 3.3 MB/s eta 0:00:03
   --------------------- ------------------ 10.4/18.9 MB 3.3 MB/s eta 0:00:03
   ---------------------- ----------------- 10.5/18.9 MB 3.3 MB/s eta 0:00:03
   ---------------------- ----------------- 10.6/18.9 MB 3.3 MB/s eta 0:00:03
   ---------------------- ----------------- 10.7/18.9 MB 3.3 MB/s eta 0:00:03
   ---------------------- ----------------- 10.8/18.9 MB 3.3 MB/s eta 0:00:03
   ----------------------- ---------------- 11.0/18.9 MB 3.4 MB/s eta 0:00:03
   ----------------------- ---------------- 11.1/18.9 MB 3.4 MB/s eta 0:00:03
   ----------------------- ---------------- 11.2/18.9 MB 3.3 MB/s eta 0:00:03
   ----------------------- ---------------- 11.3/18.9 MB 3.3 MB/s eta 0:00:03
   ------------------------ --------------- 11.4/18.9 MB 3.3 MB/s eta 0:00:03
   ------------------------ --------------- 11.6/18.9 MB 3.3 MB/s eta 0:00:03
   ------------------------ --------------- 11.7/18.9 MB 3.3 MB/s eta 0:00:03
   ------------------------ --------------- 11.8/18.9 MB 3.2 MB/s eta 0:00:03
   ------------------------- -------------- 11.9/18.9 MB 3.4 MB/s eta 0:00:03
   ------------------------- -------------- 12.0/18.9 MB 3.3 MB/s eta 0:00:03
   ------------------------- -------------- 12.2/18.9 MB 3.3 MB/s eta 0:00:03
   ------------------------- -------------- 12.3/18.9 MB 3.2 MB/s eta 0:00:03
   -------------------------- ------------- 12.4/18.9 MB 3.3 MB/s eta 0:00:02
   -------------------------- ------------- 12.5/18.9 MB 3.3 MB/s eta 0:00:02
   -------------------------- ------------- 12.6/18.9 MB 3.3 MB/s eta 0:00:02
   --------------------------- ------------ 12.8/18.9 MB 3.3 MB/s eta 0:00:02
   --------------------------- ------------ 12.9/18.9 MB 3.2 MB/s eta 0:00:02
   --------------------------- ------------ 13.0/18.9 MB 3.2 MB/s eta 0:00:02
   --------------------------- ------------ 13.1/18.9 MB 3.2 MB/s eta 0:00:02
   ---------------------------- ----------- 13.3/18.9 MB 3.2 MB/s eta 0:00:02
   ---------------------------- ----------- 13.4/18.9 MB 3.2 MB/s eta 0:00:02
   ---------------------------- ----------- 13.5/18.9 MB 3.2 MB/s eta 0:00:02
   ---------------------------- ----------- 13.6/18.9 MB 3.2 MB/s eta 0:00:02
   ----------------------------- ---------- 13.7/18.9 MB 3.1 MB/s eta 0:00:02
   ----------------------------- ---------- 13.9/18.9 MB 3.1 MB/s eta 0:00:02
   ----------------------------- ---------- 14.0/18.9 MB 3.1 MB/s eta 0:00:02
   ----------------------------- ---------- 14.1/18.9 MB 3.1 MB/s eta 0:00:02
   ------------------------------ --------- 14.2/18.9 MB 3.1 MB/s eta 0:00:02
   ------------------------------ --------- 14.4/18.9 MB 3.1 MB/s eta 0:00:02
   ------------------------------ --------- 14.5/18.9 MB 3.1 MB/s eta 0:00:02
   ------------------------------ --------- 14.6/18.9 MB 3.1 MB/s eta 0:00:02
   ------------------------------- -------- 14.7/18.9 MB 3.0 MB/s eta 0:00:02
   ------------------------------- -------- 14.9/18.9 MB 3.0 MB/s eta 0:00:02
   ------------------------------- -------- 15.0/18.9 MB 3.0 MB/s eta 0:00:02
   -------------------------------- ------- 15.1/18.9 MB 3.0 MB/s eta 0:00:02
   -------------------------------- ------- 15.2/18.9 MB 3.0 MB/s eta 0:00:02
   -------------------------------- ------- 15.4/18.9 MB 3.0 MB/s eta 0:00:02
   -------------------------------- ------- 15.5/18.9 MB 3.0 MB/s eta 0:00:02
   --------------------------------- ------ 15.6/18.9 MB 2.9 MB/s eta 0:00:02
   --------------------------------- ------ 15.7/18.9 MB 2.9 MB/s eta 0:00:02
   --------------------------------- ------ 15.9/18.9 MB 2.9 MB/s eta 0:00:02
   --------------------------------- ------ 16.0/18.9 MB 2.9 MB/s eta 0:00:01
   ---------------------------------- ----- 16.1/18.9 MB 2.9 MB/s eta 0:00:01
   ---------------------------------- ----- 16.2/18.9 MB 2.9 MB/s eta 0:00:01
   ---------------------------------- ----- 16.4/18.9 MB 2.9 MB/s eta 0:00:01
   ----------------------------------- ---- 16.5/18.9 MB 2.9 MB/s eta 0:00:01
   ----------------------------------- ---- 16.6/18.9 MB 2.9 MB/s eta 0:00:01
   ----------------------------------- ---- 16.8/18.9 MB 2.9 MB/s eta 0:00:01
   ----------------------------------- ---- 16.9/18.9 MB 2.9 MB/s eta 0:00:01
   ------------------------------------ --- 17.0/18.9 MB 2.8 MB/s eta 0:00:01
   ------------------------------------ --- 17.2/18.9 MB 2.8 MB/s eta 0:00:01
   ------------------------------------ --- 17.3/18.9 MB 2.8 MB/s eta 0:00:01
   ------------------------------------ --- 17.4/18.9 MB 2.8 MB/s eta 0:00:01
   ------------------------------------- -- 17.6/18.9 MB 2.8 MB/s eta 0:00:01
   ------------------------------------- -- 17.7/18.9 MB 2.8 MB/s eta 0:00:01
   ------------------------------------- -- 17.8/18.9 MB 2.8 MB/s eta 0:00:01
   -------------------------------------- - 18.0/18.9 MB 2.8 MB/s eta 0:00:01
   -------------------------------------- - 18.1/18.9 MB 2.8 MB/s eta 0:00:01
   -------------------------------------- - 18.2/18.9 MB 2.8 MB/s eta 0:00:01
   -------------------------------------- - 18.4/18.9 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------  18.5/18.9 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  18.6/18.9 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------  18.8/18.9 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  18.9/18.9 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------- 18.9/18.9 MB 2.7 MB/s eta 0:00:00
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.13.2

In [8]:
import pandas as pd
import numpy as np
import pickle
import faiss

In [9]:
hotels = pd.read_csv("hotels.csv")
places = pd.read_csv("places.csv")
restaurants = pd.read_csv("restaurants.csv")

print("Hotels:", hotels.shape)
display(hotels.head())

print("Places:", places.shape)
display(places.head())

print("Restaurants:", restaurants.shape)
display(restaurants.head())

Hotels: (2550, 10)

,id,city,Hotel Name,Price,Review Score (/10),Hotel URL,Description,Latitude,Longitude,Distance (km)
0,1,alexandria,Tolip Hotel Alexandria,543.0,8.2,https://www.booking.com/hotel/eg/royal-tulip-a...,This 5-star hotel in Alexandria offers an outd...,31.231793,29.946027,180.59
1,2,alexandria,Rixos Montaza Alexandria,779.0,9.1,https://www.booking.com/hotel/eg/rixos-montaza...,Prime Location: Rixos Montaza Alexandria in Al...,31.288405,30.015993,180.78
2,3,alexandria,Alexandria Ap,140.0,7.5,https://www.booking.com/hotel/eg/alexandria-ap...,Comfortable Accommodations: Alexandria Ap in A...,31.240590,29.956584,180.61
3,4,alexandria,Hilton Alexandria Green Plaza,343.0,8.4,https://www.booking.com/hotel/eg/hilton-alexan...,"On site of Green Plaza Mall, this Hilton is on...",31.206543,29.965575,177.28
4,5,alexandria,Palestine Montaza Alexandria,700.0,8.4,https://www.booking.com/hotel/eg/helnan-palest...,Set on 350 acres of lush gardens overlooking a...,31.287894,30.017722,180.63

Places: (391, 10)

,id,City,Title,Rating,Reviews,Description,Tips,Address,Timings,Ticket Price
0,1,cairo,Pyramids Of Giza,4.0,7224.0,The most famous of the Seven Wonders of the An...,Avoid visiting Pyramids of Giza at night time....,"Al Ahram, Al Haram, Giza, Egypt, Cairo",07:00 am - 07:00 pm,60.0
1,2,cairo,Keops Pyramid,NaN,NaN,Take a historic walk through the ancient icons...,Guided tours are available and recommended.\nD...,"Al Haram, Nazlet El-Semman, Al Haram, Giza Gov...",08:00 am - 05:00 pm,NaN
2,3,cairo,Sphinx,4.0,6728.0,"The Terrifying One, as the Great Sphinx is kno...",Confirm timings before visiting the Sphinx.\nP...,"Al Ahram, Giza, Egypt, Cairo",08:00 am - 05:00 pm,20.0
3,4,cairo,Islamic Cairo,4.0,2752.0,Islamic Cairo is a historic area that was crea...,Guided tours are available.,"Al Gamaleyah, Qesm Gamaleyah, Cairo Governorat...",24-hrs,NaN
4,5,cairo,The Egyptian Museum,4.0,5544.0,This Egyptian museum is located at Tahrir squa...,Photography is strictly prohibited.\nCameras w...,"Tahrir Square, Meret Basha, Ismailia, Qasr an ...",09:00 am - 07:00 pm,75.0

Restaurants: (1225, 11)

,id,city,Restaurant,Location,Cuisines,URL,Total_Items,Prices_List,Min_Price,Max_Price,Avg_Price
0,1,alexandria,Teus,"inSemouha - Semouha Sporting Club,Egypt","Sandwiches, Burgers, Fast Food",https://www.talabat.com/egypt/restaurant/66109...,183,"[158.0, 137.0, 85.0, 165.0, 56.0, 28.0, 137.0,...",11.0,199.0,89.818713
1,2,alexandria,D's Patisserie,"inSemouha,Egypt","Bakery & Pastry, Desserts, Arabic sweets",https://www.talabat.com/egypt/restaurant/73112...,16,"[65.0, 200.0, 110.0, 75.0, 250.0, 85.0, 180.0,...",65.0,250.0,135.625000
2,3,alexandria,T-lab,"inKafr Abdo,Egypt","Cafe, Beverages",https://www.talabat.com/egypt/restaurant/78301...,50,"[230.0, 230.0, 230.0, 20.0]",20.0,230.0,177.500000
3,4,alexandria,The Canteen,"inKafr Abdo,Egypt","Healthy , Chicken, Salad, Sandwiches",https://www.talabat.com/egypt/restaurant/51731...,7,"[179.0, 249.0, 249.0, 179.0, 239.0, 249.0, 249.0]",179.0,249.0,227.571429
4,5,alexandria,Ma3booj,"inIbrahimia,Egypt","Arabic, Saudi, Kuwaiti",https://www.talabat.com/egypt/restaurant/76058...,48,"[50.0, 60.0, 80.0, 99.0, 149.0, 149.0, 129.0, ...",15.0,500.0,77.369565

In [10]:
embeddings = np.load("embeddings.npy")
print("Embeddings shape:", embeddings.shape)

Embeddings shape: (4166, 384)

In [11]:
with open("travel_metadata.pkl", "rb") as f:
    metadata = pickle.load(f)

print(type(metadata))
print(metadata[:3])  # preview first 3 entries

<class 'pandas.core.frame.DataFrame'>
    type                      name        city  price  rating  \
0  hotel    Tolip Hotel Alexandria  alexandria  543.0     8.2
1  hotel  Rixos Montaza Alexandria  alexandria  779.0     9.1
2  hotel             Alexandria Ap  alexandria  140.0     7.5

                                                text
0  Hotel Tolip Hotel Alexandria in alexandria wit...
1  Hotel Rixos Montaza Alexandria in alexandria w...
2  Hotel Alexandria Ap in alexandria with price 1...

In [12]:
index = faiss.read_index("travel_vector_db.index")
print("Total vectors:", index.ntotal)
print("Dimensions:", index.d)

Total vectors: 4166
Dimensions: 384

In [13]:
with open("db_queries.sql") as f:
    print(f.read())

with open("insert_data.sql") as f:
    print(f.read())

CREATE DATABASE eg_trip_db;
USE eg_trip_db;


-- =============================================
-- 1. dim_hotels
-- =============================================
CREATE TABLE dim_hotels (
    hotel_id      INT            IDENTITY(1,1)  PRIMARY KEY,
    city          NVARCHAR(100)  NOT NULL,
    hotel_name    NVARCHAR(255)  NOT NULL,
    price         FLOAT          NULL,
    review_score  DECIMAL(3,1)   NULL,
    hotel_url     NVARCHAR(MAX)  NULL,
    description   NVARCHAR(MAX)  NULL,
    latitude      FLOAT          NULL,
    longitude     FLOAT          NULL,
    distance_km   DECIMAL(6,2)   NULL,
);

-- =============================================
-- 2. dim_places
-- =============================================
CREATE TABLE dim_places (
    place_id      INT            IDENTITY(1,1)  PRIMARY KEY,
    city          NVARCHAR(100)  NOT NULL,
    title         NVARCHAR(255)  NOT NULL,
    rating        DECIMAL(3,1)   NULL,
    reviews       FLOAT          NULL,
    description   NVARCHAR(MAX)  NULL,
    tips          NVARCHAR(MAX)  NULL,
    address       NVARCHAR(500)  NULL,
    timings       NVARCHAR(300)  NULL,
    ticket_price  FLOAT          NULL
);


-- =============================================
-- 3. dim_restaurants
-- =============================================
CREATE TABLE dim_restaurants (
    restaurant_id   INT            IDENTITY(1,1)  PRIMARY KEY,
    city            NVARCHAR(100)  NOT NULL,
    restaurant_name NVARCHAR(255)  NOT NULL,
    location        NVARCHAR(500)  NULL,
    cuisines        NVARCHAR(500)  NULL,
    url             NVARCHAR(MAX)  NULL,
    total_items     INT            NULL,
    prices_list     NVARCHAR(MAX)  NULL,
    min_price       FLOAT          NULL,
    max_price       FLOAT          NULL,
    avg_price       FLOAT          NULL
);


-- =============================================
-- 4. fact_trip
-- =============================================
CREATE TABLE fact_trip (
    trip_id        BIGINT  IDENTITY(1,1)  PRIMARY KEY,
    hotel_id       INT     NULL,
    restaurant_id  INT     NULL,
    place_id       INT     NULL,

    CONSTRAINT FK_trip_hotel      FOREIGN KEY (hotel_id)
        REFERENCES dim_hotels      (hotel_id)      ON DELETE SET NULL,

    CONSTRAINT FK_trip_restaurant FOREIGN KEY (restaurant_id)
        REFERENCES dim_restaurants (restaurant_id) ON DELETE SET NULL,

    CONSTRAINT FK_trip_place      FOREIGN KEY (place_id)
        REFERENCES dim_places      (place_id)      ON DELETE SET NULL
);
-- =============================================
-- STEP 1: Insert into dim_places
-- =============================================
BULK INSERT dim_places
FROM 'places.csv'
WITH (
    FORMAT          = 'CSV',
    FIRSTROW        = 2,          -- skip header row
    FIELDTERMINATOR = ',',
    ROWTERMINATOR   = '\n',
    CODEPAGE        = '65001'     -- UTF-8
);


-- =============================================
-- STEP 2: Insert into dim_restaurants
-- =============================================
BULK INSERT dim_restaurants
FROM 'restaurants.csv'
WITH (
    FORMAT          = 'CSV',
    FIRSTROW        = 2,
    FIELDTERMINATOR = ',',
    ROWTERMINATOR   = '\n',
    CODEPAGE        = '65001'
);


-- =============================================
-- STEP 3: Insert into dim_hotels
-- =============================================
BULK INSERT dim_hotels
FROM 'hotels.csv'
WITH (
    FORMAT          = 'CSV',
    FIRSTROW        = 2,
    FIELDTERMINATOR = ',',
    ROWTERMINATOR   = '\n',
    CODEPAGE        = '65001'
);